Created documentation page for generating manifest files from search api, and a link to that page from index.md
hubmapconsortium/documentation pull request #9
Opened 2024-07-11 23:22 UTC by DerekFurstPitt

2024-07-12 15:42 UTC, yuanzhou requested changes

2024-07-12 15:42 UTC, yuanzhou commented on docs/clt/generate-manifest.md
> +"https://search.api.hubmapconsortium.org", we get "https://search.api.hubmapconsortium.org/search?produce-clt-manifest=true".
Use `https://search.api.hubmapconsortium.org/v3/` as base URL

2024-07-12 15:42 UTC, yuanzhou commented on docs/clt/generate-manifest.md
> +https://search.api.org/hubmapconsortium.org/search?produce-clt-manifest=true"
Use `https://search.api.hubmapconsortium.org/v3/` as base URL

2024-07-12 15:42 UTC, yuanzhou commented on docs/clt/generate-manifest.md
> +            "entity_type.keyword": "Sample"
I don't think Sample would result any manifest... Use Dataset instead.

2024-07-15 18:09 UTC, shirey requested changes
@DerekFurstPitt Did you make changes to the openapi "*spec.yaml" file to include instructions for ?produce-clt-manifest=true?

Also, please add some content to generate-manifest.md that explains how/has an example of saving the manifest file and using it with the hubmap-clt.  Also, also along with this link to the clt documentation.

In the clt/index.md file-- make sure to tell folks that they can construct manifest files manually too- people are going to follow this VERY explicitly and think that this is the only way to generate manifest files.  So some thing like "Manifest files can be constructed manually as explained below or automatically using a SearchAPI query by specifying an optional argument.  More information . . ."

2024-07-15 21:32 UTC, DerekFurstPitt commented
@shirey I made some tweaks per your requests. Please take a look and let me know if any further changes are requested

2024-07-24 13:11 UTC, shirey approved these changes
Looks good

2024-07-24 14:50 UTC, yuanzhou approved these changes
Will hold off the merge until the actual features are released to PROD.

2024-07-24 20:23 UTC, merged